# Generated by Django 4.2.4 on 2023-11-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wealthwiseapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="created",
        ),
        migrations.AddField(
            model_name="item",
            name="bank_account_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="bank_balance",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="car_loan",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="credit_card_debt",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="investment_portfolio_value",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="mortgage_value",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="routing_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="student_loan",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="user_id",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
