# Generated by Django 4.2.4 on 2023-11-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wealthwiseapp", "0002_remove_item_created_item_bank_account_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
