# Generated by Django 4.2.5 on 2023-11-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wealthwiseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wealthwiseapp.userprofile')),
            ],
        ),
    ]
