# Generated by Django 4.2.5 on 2023-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthwiseapp', '0003_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cryptocurrency_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
