# Generated by Django 4.2.5 on 2023-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealthwiseapp', '0004_userprofile_cryptocurrency_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='investment_portfolio_value',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bonds_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stocks_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
